name: Run linters

on: [push, pull_request]

jobs:
  golang-ci-lint:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: v1.62.2
